[metadata]
name = neural-graphs-mice-development
version = 0.0.1
author = Rodrigo C. G. Pena
author_email = rodrigo.cerqueiragonzalezpena@unibas.ch
description = Comparing the structure of neural connections during the development of mice.
long_description = file: README.md
long_description_content_type = text/markdown
license = BSD 3-Clause License
license_files = file: LICENSE
url = https://gitlab.com/ceda-unibas/neural-graphs-mice-development
project_urls =
    Source Code = https://gitlab.com/ceda-unibas/neural-graphs-mice-development
    Issue Tracker = https://gitlab.com/ceda-unibas/neural-graphs-mice-development/-/issues
classifiers =
    Development Status :: 3 - Alpha
    Environment :: GPU
    Intended Audience :: Developers
    Intended Audience :: Education
    Intended Audience :: Science/Research
    License :: OSI Approved :: BSD License
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.10
    Operating System :: OS Independent
    Topic :: Education
    Topic :: Scientific/Engineering :: Artificial Intelligence

[options]
packages = find:
python_requires = >=3.10
include_package_data = True
install_requires =
    click>=8.1
    networkx>=2.8
    pandas>=1.4
    PyYAML>=6.0
    tqdm>=4.0

[options.extras_require]
dev =
    # Linting for code style
    flake8 >= 4.0
    ruff >= 0.3
    # Build documentation
    numpydoc >= 1.1
    memory-profiler >= 0.58
    myst-parser >= 0.15
    Sphinx >= 4.3
    sphinxcontrib-bibtex >= 2.4
    sphinx-gallery >= 0.10
    sphinx-rtd-theme >= 1.0
    sphinx-copybutton >= 0.4
    # Run tests and publish coverage stats
    pytest >= 6.2
    coverage >= 6.1
    # Build distribution archive
    build >= 0.7
    # Check and upload distribution archives to PyPI
    twine >= 3.6
    # Run Jupyter Notebooks
    jupyterlab >= 3.2
    ipympl>=0.9

[flake8]
doctests = True
exclude = docs

[coverage:run]
branch = True
source = ngmd
